server:
  port: 30083

logging:
  path: ${user.home}/${spring.application.name}
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: error

spring:
  jackson:
    default-property-inclusion: non_null


feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

sso:
  redis: redis://redis.limaila.com:6379/1,redis://redis.limaila.com:6379/2
  expire:
    second: 86400