server:
  port: 30081

logging:
  path: ${user.home}/${spring.application.name}
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: error

spring:
  data:
    mongodb:
      uri: mongodb://mongo.limaila.com/ci-user
      port: 27017
  jackson:
    default-property-inclusion: non_null
  redis:
    database: 0
    url: redis://redis.limaila.com:6379

feign:
  hystrix:
    enabled: true


rocketmq:
  name-server: www.limaila.com:9876
  producer:
    group: ${spring.application.name}




hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

es:
  address: node1.es.sizne.net:9200,node2.es.sizne.net:9200,node3.es.sizne.net:9200