server:
  port: 30081

logging:
  path: ${user.home}/${spring.application.name}
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: error

spring:
  data:
    mongodb:
      uri: mongodb://mongo.limaila.com/ci-user
      port: 27017
  jackson:
    default-property-inclusion: non_null

feign:
  hystrix:
    enabled: true


rocketmq:
  name-server: www.limaila.com:9876
  producer:
    group: ${spring.application.name}