server:
  port: 30082

logging:
  path: ${user.home}/${spring.application.name}
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: error
spring:
  data:
    mongodb:
      uri: mongodb://mongo.limaila.com/ci-order
      port: 27017
  jackson:
    default-property-inclusion: non_null


feign:
  hystrix:
    enabled: true
