server:
  port: 30082

logging:
  path: ${user.home}/${spring.application.name}
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: error
spring:
  data:
    mongodb:
      uri: mongodb://mongo.limaila.com/ci-order
      port: 27017
  cloud:
    nacos:
      discovery:
        server-addr: www.limaila.com:8848