apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ci-cloud-gateway
  labels:
    app: ci-cloud-gateway
  namespace: ci-cloud
spec:
  # 副本数
  replicas: 1
  selector:
    matchLabels:
      app: ci-cloud-gateway
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ci-cloud-gateway
    spec:
      # 允许master节点部署
#      tolerations:
#      - key: node-role.kubernetes.io/master
#        operator: Exists
#        effect: NoSchedule
      containers:
      - name: ci-cloud-gateway
        image: registry-vpc.cn-shenzhen.aliyuncs.com/huangxincheng/ci-cloud-gateway:1.1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        lifecycle:
          preStop:
            exec:
              command:
                - ls /root
        env:
        - name: JAVA_OPTS
          value: "-server -Xmx256m -Xms256m"
        volumeMounts:
        - mountPath: /root/ci-cloud-gateway
          name: logs
      volumes:
      - name: logs
        hostPath:
          path: /logs

---

# 正常情况只有网关才需要暴露nodePort。
# 暂时没有网关，故暴露nodePort
apiVersion: v1
kind: Service
metadata:
  name: ci-cloud-gateway
  namespace: ci-cloud
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30050
  selector:
    app: ci-cloud-gateway
