server:
  port: 80

spring:
  cloud:
    gateway:
      default-filters:
        - name: Hystrix
          args:
            name: fallbackCmd
            fallbackUri: forward:/fallbackCmd
        - name: Global
          args:
            handler: true
        - name: Auth
          args:
            ignoreAuthServices:
              - ci-cloud-order
              - ci-cloud-user
            ignoreAuthRoutes:
              - routeId: ci-cloud-order
                uri:
                  - /api/v1/order/get
      routes:
        - id: ci-cloud-order
          uri: lb://ci-cloud-order
          predicates:
            - name: Path
              args[pattern]: /order/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Request-Foo, Bar
        - id: ci-cloud-user
          uri: lb://ci-cloud-user
          predicates:
            - name: Path
              args[pattern]: /user/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Request-Foo, Bar

logging:
  path: ${user.home}/${spring.application.name}
  level:
    root: info
    com:
      alibaba:
        nacos:
          client:
            naming: error

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

# 启动实例化ribbon
ribbon:
  eager-load:
    enabled: true
    clients:
      - ci-cloud-user
      - ci-cloud-order



sso:
  redis: redis://redis.limaila.com:6379/1,redis://redis.limaila.com:6379/2